services:
  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports: ["4000:4000"]
  db:
    image: postgres
    restart: always
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: spacex
      POSTGRES_USER: docker0
      POSTGRES_PASSWORD: "some password TODO"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
